### ISSUE TITLE
Views 1.6 iteration improvements

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1022]
- [ ] Support AggregatedElasticSearchView and AggregatedSparqlView with composite projections - parent of #999
- [ ] Add `tag` metadata field to indices - parent of #943
- [ ] Support for querying based by`tag`- parent of #696
- [ ] Support reindexing on view updates without downtime - parent of #729 
- [ ] Support to define analyzer on ElasticSearchView/ElasticSearchProjection
- [x] Support for custom view permissions
- [x] Simplify `ProjectViewCoordinatorActor`
