### ISSUE TITLE
Default Plugins 

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1043]
In order to perform basic data curation functions and to visualize them as the current ResourceView allows.

The goal is to collapse the StudioResourceView and ResourceView into one. Right now there are two routes to navigate to them, a human-readable way and a non-human readable way. It would be nice to keep the ResourceView path such as `:orgLabel/:projectLabel/resource/:resourceId` would lead you to the singular ResourceView.

- [x] Plugins will be rendered inside the ResourceView 
- [x] Default plugins developed for Data Curators (Json, Links, History, Provenance and Graph)
- [x] Plugins to be rendered based on ACL/Identity. 
- [x] The StudioResourceView will be removed 

related https://github.com/BlueBrain/nexus/issues/1042 , https://github.com/BlueBrain/nexus/issues/1041
