### ISSUE TITLE
Plugins in Nexus Studio

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1125]
## Plugins
- [x] Neuron Morphology https://github.com/BlueBrain/nexus/issues/950
- [x] Neuron Electrophysiology https://github.com/BlueBrain/nexus/issues/1028
- [x] Administration https://github.com/BlueBrain/nexus/issues/1041
- [ ] "MINDs" Metadata https://github.com/BlueBrain/nexus/issues/1102
- [ ] Data Access https://github.com/BlueBrain/nexus/issues/1101
- [x] Image https://github.com/BlueBrain/nexus/issues/1105
- [x] Simulation @pgetta 
- [x] Simulation Campaign @pgetta 
- [x] Circuit @pgetta 
- [ ] Fact-sheet(s)
- [ ] Morphology(ies)
- [ ] Default Metadata

**Comment by adulbrich** [comment]
Add extra issues from improvements to the list
