### ISSUE TITLE
Review login flow

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1149]
## Tasks

- [x] Workflow of the login flow
- [x] Review of the existing flow (UX perspective)
- [x] Propose improvement
- [x] Login bug refactoring https://github.com/BlueBrain/nexus/issues/1674
- [ ] Implement (create new issue?)

## Proposal

Check Adobe Xd (protected): https://xd.adobe.com/view/d8808b1c-6d44-43f8-86e6-f75b4c5ca1ab-8dd3/

We don't want a login page immediately when the user reaches the app, because, for public projects, users don't need to be logged in. But we can get rid of the current app login page that just creates an unnecessary hop for the user.

So instead of:

 - click on login -> go to nexus login page -> choose realm if any -> go to realm login page

We will have:

- click or hover login button -> dropdown of realms (if multiple) -> go to realm login page on click

### One Realm Active

![image](https://user-images.githubusercontent.com/11705901/95834006-b2915580-0d3c-11eb-854c-2854f2ae7d4f.png)

### Multiple Realms Active

![image](https://user-images.githubusercontent.com/11705901/95833995-ac9b7480-0d3c-11eb-8104-e8d642815702.png)
