### ISSUE TITLE
Nexus Search

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1161]
Goals of the PoC: 
- Configurable, universal, search UI
- Validation with users
- Default Search, MINDs search, Literature
- Deployed somewhere for feedback

Internal requirements: https://bbpteam.epfl.ch/project/spaces/display/NEX/Product+Requirements%3A+Nexus+Search

- [x] architecture proposal document @kenjinp 
- [x] architecture alignment
- [ ] deployment on prod (where the data lives)
- [x] UI for search (see first draft below)
- [ ] #1163 search nexus resources (MINDS, default)
- [x] #1164 search literature (embedding) (ticket not relevant anymore)
- [x] generic result card for all resource types (if no specific card configured)
- [ ] specific cards for specific resource types (user configurable)

![image](https://user-images.githubusercontent.com/11705901/81786312-c15eac80-94ff-11ea-95ad-470da52c828b.png)

**Comment by kenjinp** [comment]
Will be rolled into Fusion
