### ISSUE TITLE
Wireframes: Studios Home

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1227]
ES: 
SP 1

part of https://github.com/BlueBrain/nexus/issues/1226

- [x] HOME-001 | As a user, I want to see my own projects, as well as projects from the organizations I belong to on my homepage, in order to access a specific project. | 1 Must Have | 3 BlueBrain/nexus#1283

- [x] HOME-002 | As a user, I want to see a list of new notifications on my home page, related to the projects I have access to, in order to quickly see what has been happening since my last visit. | 2 Should Have |  BlueBrain/nexus#1284

- [x] ~~HOME-003 | As a user, I want to customize the list of new activities that are shown on my home page, in order to filter out the information I deem less relevant. | 3 Could Have |   ????? (Will do later)~~

- [x] HOME-004 | As a user, I want to be able to create a new personal project for myself, in order to organize, structure, and plan my research in my personal scientific project. | 1 Must Have | 3 BlueBrain/nexus#1282

- [x] HOME-005 | As an organization admin, I want to be able to create a new project for the organization, in order for people to start contributing to it. | 2 Should Have |  BlueBrain/nexus#1285

- [x] HOME-006 | As a user, I want to click on a project and access its dedicated page, in order to have greater detail about the project. | 1 Must Have | 3 BlueBrain/nexus#1283

**Comment by adulbrich** [comment]
Need to update with latest wireframes with updated sidebar, all subapps (incl. Grafana, WebProetege, and maybe Atlas), then create issue for dev.
