### ISSUE TITLE
Wireframes: Activity Page

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1247]
# What is an activity?

An  activity describes a chunk of work to be performed in the scope of a project. 
Activities can contain sub-activities. 
An activity produces or leverages work artifacts.

Proposed addition: An activity is defined in the context of W3C Prov-O. Can we constraint the activity for a user seamlessly in order to enable Prov-O?

part of #1226

- [x]  ACTI-001 | As a user, I want to define or edit the activity metadata, in order to convey the activity overview. | 1 Must Have | 3 #1266
-- | -- | -- | --
- [x]   ~~ACTI-002 | As a user, I can invite contributors to an activity only, in order for them to contribute to a specific activity and not the whole project. | 4 Won't Do |~~
- [x] ACTI-003a | As a user, I can manually add an existing work artifact to the activity, in order to make it visible to others in the project or activity. | 1 Must Have | 3 (existing) + 5 (sharing) https://github.com/BlueBrain/nexus/issues/1271
- [x] ACTI-003b | As a user, I can manually create a new work artifact (if that work artifact allows it) to the activity, in order to make it visible to others in the project or activity. | 1 Must Have | 8 BlueBrain/nexus#1264
- [ ] ACTI-003c | As a user, I want to specify if the work artifacts serves as input for that activity, or if that work artifact will be produced by that activity. | 1 Must Have | 2
- [ ] ACTI-003d | As an experimenter, I want to add my experimental data through a form, in order to make it available in project/activity. | 1 Must Have | 2 (linked to ACTI-003b)
- [x] ACTI-004 | As a user, I can get the instructions to link my work artifact programmatically in the activity in order to make it available and traceable in the project. | 1 Must Have | 2 (maybe a sample py notebook) PUSH ARTIFACTS
- [x] ACTI-005 | As a user, I can see all the work artifacts that have been created in an activity, and by whom, in order to visualize them. | 1 Must Have | 5 BlueBrain/nexus#1272
- [x] ACTI-006 | As a user, I want to define the activities related to this one, either in or out, in order to make the activity flow visible. | 1 Must Have | 3
- [x] ACTI-010 | As a user, I want to leave comment (if permissions allow) on the activity, in order to communicate with my peers or track notes. | 2 Should Have |  BlueBrain/nexus#1274
- [x] ACTI-014 | As a user, I can click on a work artifact, in order to access to work artifact page. | 1 Must Have | 3 BlueBrain/nexus#1278
- [x] ACTI-015 | As a user, I can get the work artifact programmatically from that activity in order to make use of it outside the software. | 1 Must Have | 1 READ ARTIFACTS

**Comment by kenjinp** [comment]
I think an Activity is like a board that can contain any number of activities or datasets or links to documents to organize them. In that way, I'm not sure the word "Activity" fully describes what is being done there. Should there be two types of "Boards"? Boards with Status and I/O = Activity, a Board with just links and data for organization and documentation is just a Board?
