### ISSUE TITLE
Fusion Workflow MVP

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1263]
# Features (foundation)

Larger issues that might need more work should be denoted by ⚠️ .
The main issues and features should be part of milestone 1.5.

The latest designs are extracted and available in this presentation with descriptions: https://docs.google.com/presentation/d/1dpNTR9rN9KCzRHEzXYHBdPwb4sh4u_3VaW1FClngokc/edit#slide=id.p

## Prerequisites
https://github.com/BlueBrain/nexus/issues/1454

- [x] project data model
- [x] activity data model
- [x] template structure
- [x] 🆕  implement new data model (and confirm naming)

## Fusion Interface Redesign

- [x] foundations https://github.com/BlueBrain/nexus/issues/1292
- [x] Studio Homepage: list of studios https://github.com/BlueBrain/nexus/issues/1329 
- [x] (Admin Homepage): current nexus-web org/proj https://github.com/BlueBrain/nexus/issues/1310
- [x] routes migration https://github.com/BlueBrain/nexus/issues/1336
- [x] 🆕  configurable button to doc page for code snippets in header

### New Projects Subapps Home Page (Projects)

- [x] name of sub-app https://github.com/BlueBrain/nexus/issues/1453
- [x] data model for workflow projects https://github.com/BlueBrain/nexus/issues/1454
- [x] create new sub-app space "Projects" https://github.com/BlueBrain/nexus/issues/1456
- [x] ⚠️ project "card" with important summary indicators (e.g. status, number of activities, members, type of project, target date) https://github.com/BlueBrain/nexus/issues/1460
- [x] list existing personal projects https://github.com/BlueBrain/nexus/issues/1458
- [x] list existing organizational projects https://github.com/BlueBrain/nexus/issues/1459
- [x] sort the list of projects https://github.com/BlueBrain/nexus/issues/1462
- [x] ⚠️ create a new personal project https://github.com/BlueBrain/nexus/issues/1457
- [x] access archived or past projects https://github.com/BlueBrain/nexus/issues/1463
- [ ] ⏬  search the list of projects https://github.com/BlueBrain/nexus/issues/1461
- [ ] ⏬  add members to project https://github.com/BlueBrain/nexus/issues/1563
- [ ] ⏬  choose access level for members (read, write, ...)

### Project View Page

- [x] instantiate project view in /projects subapp https://github.com/BlueBrain/nexus/issues/1564
- [x] project view: header https://github.com/BlueBrain/nexus/issues/1565
- [x] project metadata collapsible edit pane https://github.com/BlueBrain/nexus/issues/1568

### Project View Page

- [x] ⚠️ activity card https://github.com/BlueBrain/nexus/issues/1566
- [x] ⚠️ add new activity button and form (aware of depth in project) https://github.com/BlueBrain/nexus/issues/1569
- [x] 🆕  search activity types (labels) in target ontology in order to create a step
- [x] ⚠️ add new activities from template button and form (aware of depth in the project) https://github.com/BlueBrain/nexus/issues/1570
- [x] 🆕  add notification icon
- [x] 🆕  notifications = list of non-linked activities
- [x] 🆕  notification actions: link activity to an existing step, or create a new step
- [x] 🆕  link prov:Activity to nxv:WorkflowStep manually for every new prov:Activity in the project (new form)
- [x] link activity to parent or child https://github.com/BlueBrain/nexus/issues/1592
- [x] template card https://github.com/BlueBrain/nexus/issues/1571
- [ ] (1.6) template library
- [ ] ⏩  project status computed based on activity statuses
- [ ] ⏬  ability to draw a relation between cards on canvas
- [x] ♨️  interactive project/actvity canvas with activity cards https://github.com/BlueBrain/nexus/issues/1567
- [x] ♨️  link activity to previous/next activity https://github.com/BlueBrain/nexus/issues/1628

### Activity View Pages

- [x] clicking on the activity card brings the user to that activity
- [x] activity header with depth breadcrumbs https://github.com/BlueBrain/nexus/issues/1620
- [x] activity metadata collapsible edit pane https://github.com/BlueBrain/nexus/issues/1621

## Resource Management

- [x] project/activity collapsible resources pane https://github.com/BlueBrain/nexus/issues/1651
- [x] list all entities and agents related to that activity https://github.com/BlueBrain/nexus/issues/1652
- [x] clicking on a resource displays resource view https://github.com/BlueBrain/nexus/issues/1678
- [x] "link code" button (SoftwareAgent with path to code and prov properties) https://github.com/BlueBrain/nexus/issues/1656 
- [x] 🆕  resource pane: activities view
- [x] 🆕  move “link code” button to activities view + adapt form
- [x] 🆕  resource pane: notes view
- [x] 🆕  move "add note" button to notes view
- [x] 🆕  resource pane: input view
- [x] ⏬  resource pane sidebar https://github.com/BlueBrain/nexus/issues/1653
- [x] ⏬  filter resources by: code, input data, output data (and later docs) https://github.com/BlueBrain/nexus/issues/1655
- [x] ⏬  search resources by label/name/description https://github.com/BlueBrain/nexus/issues/1654
- [x] create input from search dataset

## Identified Improvements

- [x] by default, have the resource pane open https://github.com/BlueBrain/nexus/issues/1763
- [x] group shared projects by organizations (or better, add the organization on the project card)
- [x] the arrow icon next to Personal/Shared/Archived Projects is confusing (looks like it collapsed while it orders)
- [x] ability to click on the sub-activity of an activity card to go to that specific sub-activity https://github.com/BlueBrain/nexus/issues/1761
- [x] collapsible side menu https://github.com/BlueBrain/nexus/issues/1322
- [x] remove status twice from project card https://github.com/BlueBrain/nexus/issues/1580
- [x] error message when creating a project https://github.com/BlueBrain/nexus/issues/1562
- [x] sub-activity title character length in activity card https://github.com/BlueBrain/nexus/issues/1665
- [x] activity card height https://github.com/BlueBrain/nexus/issues/1666
- [x] ♨️  Replace the "Inputs" tab with a "Data" tab which is an adapted version of Studio https://github.com/BlueBrain/nexus/issues/1964
- [ ] ♨️  Export Data from Search (query and dataset, leveraging local storage) should work in the Workflow Data tab https://github.com/BlueBrain/nexus/issues/1965
- [x] ♨️  Export Data should work at the resource level as well (leveraging local storage) https://github.com/BlueBrain/nexus/issues/1966
- [x] ♨️  Default Workflow Project configuration https://github.com/BlueBrain/nexus/issues/1961
- [x] ♨️  ACLs for Workflow Project creation https://github.com/BlueBrain/nexus/issues/1960
- [x] ♨️  a workflow step can be informed by more than one other workflow step https://github.com/BlueBrain/nexus/issues/1936
- [ ] ♨️  add info icon for some elements (such as parent activity) to inform the user
- [ ] ♨️  Proper project editing form (workflows and projects)
- [x] ♨️  update project card with the correct number of activities and collaborators https://github.com/BlueBrain/nexus/issues/1694
- [x] ♨️  color code or add an icon on the activity page to show active status
- [ ] ⏩  all external URLs to open in new window https://github.com/BlueBrain/nexus/issues/1315
- [ ] ⏩  plugin jank https://github.com/BlueBrain/nexus/issues/1078
- [ ] ⏩  progress in % on activity card https://github.com/BlueBrain/nexus/issues/1636
- [ ] ⏩  refresh project list after project creation https://github.com/BlueBrain/nexus/issues/1668
- [ ] ⏩  Allow instance configurable default projects
- [ ] svg import https://github.com/BlueBrain/nexus/issues/1553
- [ ] acl message description https://github.com/BlueBrain/nexus/issues/1412
- [ ] real-time updates https://github.com/BlueBrain/nexus/issues/1395
- [ ] add git hook https://github.com/BlueBrain/nexus/issues/1357
- [ ] sidebar selection icon color https://github.com/BlueBrain/nexus/issues/1324
- [ ] (different) line types between activities https://github.com/BlueBrain/nexus/issues/1667
- [ ] align design across all sub-apps (e.g. project creation button in admin vs projects)
- [ ] Show latest opened project at the top of the Projects list
- [ ] Visual clue as to which type of project we are in (for example personal or organization BBP)
- [ ] ability to filter the projects by organizations
- [ ] show scrollbar on activity or project info pane if the content is too long for a page
- [ ] ability to change the height of the resource pane
- [ ] the activity card shows the description instead of the summary (design needed)
- [ ] provide more context/preview about the activity in the notifications or when linking/creating a step from notification (the first idea is to at least add the activity type to the list)
- [ ] ⏬  an unlinked activity in notifications has to have the prov:Activity type to be detected, in the future we should look directly for subclassOf prov:Activity in the target ontology

## Unidentified Bugs

- [ ] @samuel-kerrien  "_I filled the project form (Personal, title, description and due date) and pressed the create button.
    got an error message: "Supplied authentication is not authorized to access this resource"._"
- [ ] @samuel-kerrien    "_"Project info" button isn't opening panel in the Home or sub-activities;_" cannot reproduce
- [ ] cannot create a new project in Staging https://github.com/BlueBrain/nexus/issues/1741

## ♨️  Identified Bugs

- [x] "Failed to load activities" every time step is loaded https://github.com/BlueBrain/nexus/issues/1951
- [ ] infinite loading on project creation form https://github.com/BlueBrain/nexus/issues/1669
- [ ] org not created for bbp realm https://github.com/BlueBrain/nexus/issues/1670
- [ ] org deprecation issue https://github.com/BlueBrain/nexus/issues/1671
- [x] edit project button does not work on card https://github.com/BlueBrain/nexus/issues/1672
- [x] when editing and saving sub-activity through activity information panel, the activity moves to project root https://github.com/BlueBrain/nexus/issues/1745
- [x] cannot assign a sibling for an existing (sub-)activity https://github.com/BlueBrain/nexus/issues/1746
- [x] cannot edit the sibling of an existing activity https://github.com/BlueBrain/nexus/issues/1747

### Notebooks

- [x] "Preview Notebook" plugin
- [ ] "Open Notebook in App" specific plugin

If the notebook is linked to an activity:

- [ ] "Get Input Data" Snippet Plugin
- [ ] "Register Output Data" Snippet Plugin

## Forms (see Collapsible Resource Pane)

- [ ] (1.6) "link or add data" button (search + basic dataset upload)
  - users can upload their own files (like in Admin) and fill the basic dataset metadata
  - users can use the Search app to find relevant datasets and bring them into the correct activity
- [ ] (1.6) copy code snippets to get input entities https://github.com/BlueBrain/nexus/issues/1657
- [ ] (1.6) ⚠️ add data or code flow (through separate sub-app?), with full type support

[Requirements (protected)](https://docs.google.com/document/d/1CTQZFYHvoQdZuYWrK7bdgGgPGlu8AHUwTvgPfQmfXMY/edit)
Planned for 1.6 (detailed form).
