### ISSUE TITLE
V1.4 Documentation updates

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1375]
Remember to push changes to the branch `1.4.0_docs`.

Remember to test locally the final result of the docs by running `sbt build-docs`. Once finished, visit with the browser: file://{local_path_to_nexus_repo}/nexus/docs/target/site/docs/index.html

List of pages to be done in order to migrate the documentation to the v.1.4 structure:

- [x] Main page (to be updated) - parent of #1358
- [x] QuickStart Guide - parent of #1359
- [x] QuickStart Guide --> Understanding Knowledge Graphs - parent of #1360
- [x] QuickStart Guide --> Try Nexus - parent of #1361
- [x] QuickStart Guide --> Running Nexus - parent of #1377
- [X] Releases - parent of #1201
- [x] Roadmap - parent of #1362
- [x] Nexus Delta - parent of #1363
- [x] Nexus Delta --> Architecture - parent of #1365
- [X] Nexus Delta --> API Reference - parent of #1202 
- [x] Nexus Delta --> Benchmarks - parent of  #1366
- [x] Nexus Fusion - parent of #1367
- [x] Nexus Fusion --> Architecture - parent of #1368
- [x] Nexus Fusion --> Plugins - parent of #1369
- [x] Nexus Fusion --> Studio - parent of #1370
- [x] Nexus Fusion --> Admin - parent of #1371
- [x] Nexus Fusion --> Add your own APP - parent of #1372
- [x] Nexus Forge - parent of #1373
- [x] Utilities (Nexus.js, Nexus CLI, Nexus Python SDK) - parent of #1374
- [x] FAQ
