### ISSUE TITLE
Rate limit polling on the primary store during indexing

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1535]
- [x] #2462 Investigate cassandra pub/subs in order to reduce polling intervals but retain performance
- [x] #2461 Passivate view streams after an idleTimeout
- [x] #2460 Start project or organizations streams from an offset different than NoOffset
