### ISSUE TITLE
Global Search MVP

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1552]
> DKE has already put together a MINDS based Elasticsearch index in the following Nexus project: [public > sscx](https://bbp.epfl.ch/nexus/web/admin/public/sscx). Here is the corresponding [mapping](https://bbp.epfl.ch/nexus/web/public/sscx/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fviews%2Fes%2Fdataset) and here is the [ES query editor](https://bbp.epfl.ch/nexus/web/admin/public/sscx/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fviews%2Fes%2Fdataset/_search) for it.

## ✅  Iteration 1 

Implement a simple search sub-app using aggregateESView on the default ES index.

Target Facets:

- normal Nexus API vocab, like "@type" and so on. 

Limitations: 

- Max amount of projects indexable around 15 due to ElasticSearchAPI backend URL call limitation.
- Will simply target defaultElasticSearch views.

Tasks:

- [x] create and initialize search sub-app https://github.com/BlueBrain/nexus/issues/1702
- [x] add a search field in Fusion header (all sub-apps) with redirect and params for context https://github.com/BlueBrain/nexus/issues/1703
- [x] configure aggregate ES view
- [x] config-based aggregateESView target https://github.com/BlueBrain/nexus/issues/1704
- [x] search app sidebar for: https://github.com/BlueBrain/nexus/issues/1705 (using search-ui?)
  - text search
  - facet for project selection
  - facet for type selection
- [x] main app body for displaying search results: (using search-ui?) https://github.com/BlueBrain/nexus/issues/1706
  - list of results
  - ability to choose the number of results per page
  - navigate between pages
  - seeing the total number of results on top
- [x] default result card https://github.com/BlueBrain/nexus/issues/1707
- [x] clicking on resource card opens resource view with plugins

❓ What's the best practice for displaying types in the facets?

## Iteration 2

Use the MINDS index instead, creating UI facets based on the index.

Target Facets:

- MINDS fields, such as BrainLocation. 

Limitations:

- Max amount of projects indexable around 15 due to ElasticSearchAPI backend URL call limitation.
- Will target bespoke MINDS indexes, either simple ES or Composite Views.

Tasks:

- [x] derive facets from aggregate MINDS ES index (or other means of getting facets, like from config)
- [ ] get a list of facets/filters from (DKE)
- [x] get a list of searchable fields (DKE)
- [x] define MINDS ES view (for each project) (DKE)

## 🚀  Improvements

- [x] show more than 10 filters list https://github.com/BlueBrain/nexus/issues/1873
- [x] place keys for facet count tags to animate them better https://github.com/BlueBrain/nexus/issues/1879
- [x] fix search bar highlighting https://github.com/BlueBrain/nexus/issues/1878
- [x] add "File" metadata to card when available https://github.com/BlueBrain/nexus/issues/1877
- [x] fix title running off of preview card https://github.com/BlueBrain/nexus/issues/1876
- [x] fix type tag running off of preview card https://github.com/BlueBrain/nexus/issues/1875
- [x] show up to 9999 for facet count https://github.com/BlueBrain/nexus/issues/1874
- [x] show total results (more than 10k) https://github.com/BlueBrain/nexus/issues/1872
- [x] display tooltip for "text..."
- [x] allow for custom result cards (same kind of mapping as for plugins)
- [x] Export Dataset to workflow
- [x] Copy Query: out-of-project resources : Design
- [ ] the autocomplete is not the right size when there's already text and the search box expands
- [x] collapsable facets (max 10 then expand)
- [x] search for the filters (list is too long)
- [ ] display response time next to total results
- [ ] derive facets in the sidebar based on selected type
- [ ] make search field context-dependent (recognizes nexus projects) with params
- [x] "shopping cart" for selected search results/dataset https://github.com/BlueBrain/nexus/issues/2122
- [ ] searching for <project_name> sends people to the search app with only that specific project selected, targeting the default index for that project
- [x] facet display index config
- [x] facet searching / hiding improvement

## 🐞 Bugs

- [x] Fixing search csv export
- [x] Fix table sort for search sub app
- [x] Fix field table column configuration
- [x] MINDS config causing crash (sometimes)
- [x] table columns don’t display (sometimes)

## Iteration 3

Truly global search, implemented as a Nexus plugin with backend support

Target Facets:

- Facets largely automatically derived from ES mapping

Limitations:

- Might be limited by Access Rights

## Requirements

- can search with Configurable facets and can target more than one (aggregate ?) ES views
- facets will be built manually at first, then we will try to derive it from the index

[Requirement document (protected)](https://docs.google.com/document/d/1iL_QHS5QuwH3yk76to4FnwsPURuPsFeFgPdIL72o4qA/edit#)

<img width="896" alt="image" src="https://user-images.githubusercontent.com/11705901/93112411-44fbf600-f6b8-11ea-884f-9c4d51bf93aa.png">

**Comment by kenjinp** [comment]
Some design inspiration: 
https://dribbble.com/shots/14145979-Job-Search-Platform
https://dribbble.com/shots/14283979-Kafene-Merchant-Dashboard
https://dribbble.com/shots/6323387-Job-Search
https://dribbble.com/shots/14149696-Job-Search-Platform

**Comment by adulbrich** [comment]
## Mock v1

![Nexus Fusion  Search](https://user-images.githubusercontent.com/11705901/101755619-61e86f80-3ad5-11eb-81c4-229bc6d3ada1.png)

**Comment by adulbrich** [comment]
### Mock v2

![Nexus Fusion  Search v2](https://user-images.githubusercontent.com/11705901/106442373-7dd81400-647b-11eb-96b4-ac28a3937339.png)
