### ISSUE TITLE
Studio Publishing MVP

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#1728]
Non-Stretch Estimate: 41 sp for dev, 5 sp for fixes

[Requirements (protected)](https://docs.google.com/presentation/d/1ZXqAuYbRZELnlapwo6_GFsmmInW60o_jJi0OzM73Guk/edit#slide=id.p)

## Fusion

- [x] Instance configurable sidebar elements https://github.com/BlueBrain/nexus/issues/1693 1sp
- [x] Change collapse sidebar button location https://github.com/BlueBrain/nexus/issues/1692 1sp
- [x] Configurable instance logo, header color, and mention in the footer https://github.com/BlueBrain/nexus/issues/1691 3sp
- [ ] middle ware (single client cache) caching to improve performance https://github.com/BlueBrain/nexus/issues/1699 3sp

## Studios

- [x] Studio support for ES views https://github.com/BlueBrain/nexus/issues/1169 https://github.com/BlueBrain/nexus/issues/1798 10 sp
- [x] Markdown support for Studio description https://github.com/BlueBrain/nexus/issues/1735 10 sp
  - ✅  Markdown Display/Viewer 2 sp -> OK at resource level (description viewer)
  - ✅  Markdown Editor 3 sp -> OK at resource level (admin plugin)
  - ✅  Studio Edit Description
  - ✅  Resource Description Edit Plugin -> OK 
- [x] User-configurable table (selecting from available columns in ES results) 5 sp https://github.com/BlueBrain/nexus/issues/1127
- [x] Use an ES query from Search results to populate Dashboard https://github.com/BlueBrain/nexus/issues/1737 5 sp

## Search

- [x] Select a list of resources from the result listing 3 sp
  - Export all results (based on search and filters) 
  - "Create Dashboard" > Select Project/Studio/Workspace > Populates Dashboard

## Stretch Goals
- [x] Select a list of resources from the result listing https://github.com/BlueBrain/nexus/issues/1744 https://github.com/BlueBrain/nexus/issues/915
  - Export selected resources (ID-based)
- [x] download all related files
- [ ] never execute a query twice on the backend for public projects
- [x] image plugin https://github.com/BlueBrain/nexus/issues/1696
- [ ] video plugin https://github.com/BlueBrain/nexus/issues/1697
- [ ] improved metadata plugin (incl. annotations and provenance)
- [ ] Studio layout and style re-design
- [ ] mobile support https://github.com/BlueBrain/nexus/issues/1698

## Follow-up
- [ ] migrate existing studios from sparql to ES https://github.com/BlueBrain/nexus/issues/1577
- [ ] migrate studio/workspace/dashboard edit forms to edit plugins

**Comment by adulbrich** [comment]
We did not discuss having proper URLs for these Studios.
