### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2073]
Epic branch: https://github.com/BlueBrain/nexus-web/tree/2073-Table-Component-EPIC

The goal of this epic is to have a uniform table component across the app.
In fine, this means:

- Studio Dashboard leverage the Table Component
- Search results are listed in Table Component
- Workflow Steps leverage Table Component
- Table Component can be used in Plugins (e.g. listing annotations): can we make a packaged component to be imported in plugin code?

## Table UI

- Display query results in customized table
- Most buttons and sub-components are configurable

![Table v2](https://user-images.githubusercontent.com/11705901/110770855-21c29580-825a-11eb-8b1f-1ff9867bd230.png)

## Creation Form

- Creates a new TableComponent resource in the project
- Outgoing link to the parent resource

![Table Creation Form](https://user-images.githubusercontent.com/11705901/108818653-ff721c00-75b9-11eb-8573-42501a77bf4f.png)

## Edit Form (as Plugin?)

![Table Edit Plugin](https://user-images.githubusercontent.com/11705901/108818670-06009380-75ba-11eb-9396-3320b3249698.png)

## Data Model / Architecture

Resource with: 

- "@type" : "nxv:FusionTable"
- "name" : (string) 
- "description" : (string)
- "parent" : (parent resource id)
- "view" : (string) _defaultnxv:defaultSparqlIndex_
- "enableSearch" : (boolean) _default: TRUE_
- "enableInteractiveRows" : (boolean) _default: TRUE_
- "enableDownload" : (boolean) _default: TRUE_
- "enableSave" : (boolean) _default: TRUE_
- "resultsPerPage" : (integer) _default: 10_
- "dataQuery" : (string) _default: <use simple query that always works>_
- "configuration" : (array)
  - "@type" : "nxv:FusionTableColumn" 
  - "name" : (string)
  - "format" : "Date" or "Resource" or "URL" or "Image" or "Text" or "Number" or "Boolean" _default: "Text"_
  - "enableSearch" : (boolean) _default: TRUE_
  - "enableSort" : (boolean) _default: TRUE_
  - "enableFilter" : (boolean) _default: FALSE_

## Solves or paves the way to:

- Export Data from Search (query and dataset, leveraging local storage) should work in the Workflow Data tab https://github.com/BlueBrain/nexus/issues/1965
- Input and Activity tables in Workflow: clicking a row should open resource #2001 
- The Activity table query displays activity on multiple rows if multiple used or generated entities are present #2015

**Comment by Stafeeva** [comment]
Todos:
- [ ] Creation Form
- [ ] Edit Form
- [ ] Component Layout Presentation
- [ ] Support ES queries
- [ ] Support SPARQL queries
- [ ] Table Config

**Comment by adulbrich** [comment]
The "Download as CSV" should include the File location (if it exists) by default. Could we add that automatically to the CSV? It seems similar to having the ability to download Files in the Data Cart. In both cases, we need to retrieve the Files in the vicinity of the resources. @dhaneshnm @Stafeeva

**Comment by adulbrich** [comment]
@Stafeeva @dhaneshnm

- the table title is missing from the component
- I suppose the edit button does not show up if users have only read access
