### ISSUE TITLE
Studio Publishing 2021

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2162]
### Phase 1

- [ ] middle ware (single client cache) caching to improve performance #1699 3sp
- [ ] video plugin #1697
- [ ] studio landing page
- [ ] table component integration

### Phase 2

- [ ] mobile support #1698
- [ ] server-side rendered studio meta tags?
- [ ] support meta tags (react helmet?)
- [ ] custom studio URLs instead `/studio/<studio-title-slug>`
- [ ] never execute a query twice on the backend for public projects

### Migration

- [ ] migrate existing studios from sparql to ES #1577
- [ ] migrate studio/workspace/dashboard edit forms to edit plugins
