### ISSUE TITLE
Search Leftovers

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2163]
Inspiration: https://github.com/BlueBrain/nexus/issues/588

- [ ] project search bug https://github.com/BlueBrain/nexus/issues/2160
- [ ] cannot scroll down when the list of values in facet is long
- [x] review search UX
  - global vs individual projects search
  - resource vs project search
  - autocomplete
  - streamline "copy query" to create Studios
- [ ] use table component for search results (instead of list view), but keep card view
  - allow people to add to cart selected results 
- [ ] fix search bar sizing
- [ ] make search field context-dependent (recognizes nexus projects) with params
- [x] searching for <project_name> sends people to the search app with only that specific project selected, targeting the default index for that project
- [x] true (backend powered) global search
- [ ] mobile support (for publishing)

**Comment by adulbrich** [comment]
Replaced by https://github.com/BlueBrain/nexus/issues/2647 and https://github.com/BlueBrain/nexus/issues/2608
