### ISSUE TITLE
IAM v1

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#224]
Based on the evaluation of the IAM design and API for the v1 API freeze, the following items remain:

- [ ] Documentation - parent of #239 , parent of #240
- [x] Updated service structure (monitoring, health checks)
- [x] Management of permissions
- [x] Management of realms -  parent of #249 
- [x] Management of acls - parent of #251 
- [x] Indexing of path tree - parent of #237 , parent of #238 
- [x] Http routes - parent of #271
- [x] Authorization (either implicit or server flows)
- [x] User Info
- [x] Get Caller HTTP route based on token
- [ ] Integration tests
- [x] Client updates - parent of #272
- [ ] KG / Admin IAM v1 integration
