### ISSUE TITLE
Display project graph-analytics in Fusion

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2557]
Prerequisites:

- [x] #2543 Implement indexing of type counts / properties / relationships (API) 
- [x] #2544 Implement and expose routes to easily consume type properties statistics
- [x] #2545 Implement and expose routes to easily consume types relationships statistics

Check [version endpoint](https://bluebrainnexus.io/docs/delta/api/version.html) to see whether the statistics plugin is active or not. If not, the project statistics should display a message saying "Statistics are disabled in this deployment.". (This applies to all Delta plugins.)

Tasks:

- [x] Add a "Statistics" tab in the Admin interface 
- [x] update nexus.js sdk
- [x] Port existing POC branch to new tab https://github.com/BlueBrain/nexus-web/tree/POC-Project-stats
- [x] Style changes to fit the current styling
- [ ] Do not show the graph analytics tab if the plugin is not listed (check the version endpoint for plugin info)

**Comment by adulbrich** [comment]
@bogdanromanx @umbreak  the three tickets are closed, not sure now if that means we have an API for them or if it's only in a POC branch?
