### ISSUE TITLE
Admin refactoring and v1 API alignment

### ISSUE THREAD

**Issue by hygt** [BlueBrain/nexus#269]
- [ ] Documentation
- [x] Update service structure (monitoring, health checks)
- [x] Drop refined, integrate nexus-rdf & nexus sourcing
- [x] Refactor organizations - parent of #112 parent of #295
- [x] Refactor projects - parent of #111 parent of #113 
- [x] Update client
- [x] Integrate with KG and IAM parent of #337
