### ISSUE TITLE
Transition to Postgres Database

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2910]
Should we deprecate Cassandra and move to Postgres? YES

- [x] Evaluate the benchmark results 
- [x] Validate Postgres' limits in terms of high data volumes
- [x] Check current deployments/users for objections in transitioning to Postgres

**Comment by imsdu** [comment]
* Implementation
  * Complete/Refine Sourcing POC
    * Fix issues (naming, ...)
    * Add more tests (Transition to MUnit ?)
    * How to handle tests depending on Docker
    * Saving / Deleting tagged states
    * Deleting project and related resources
    * Handle id unicity across all resources in a same project
    * Add transient entity implementation
    * Add projection implementation
  * Move modules/plugins to new library (+ remove Cassandra related code / features)
    * Realms
    * Groups
    * Acls
    * Orgs
    * Projects
    * Schemas
    * Resolvers
    * Resources
    * Storages
    * Files
    * ES views
    * Blazegraph Views
    * Composite views
    * Archives
    * Project deletion
    * App
  * Change indexing strategy by streaming states instead of events
    * Elasticsearch views
    * Blazegraph views
    * Composite views
    * Graph analytics
  * Change project statistics implementation
  * Change indexing statistics implementation
  * Replace the akka distributed cache
* Migration
  * Migration from Akka Persistence Cassandra
  * Migration from Akka Persistence JDBC
* Integration tests
  * Remove Cassandra-based docker-compose files
  * Remove Cassandra-based tests
  * Update github actions
* Update documentation
  * Architecture
  * Configuration
  * ...
* Monitoring
  * Add Grafana dashboards
