### ISSUE TITLE
Multiple File storages

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#474]
- [x] Define Local (default) storage type
- [x] Define S3 storage type
- [x] Store storages on the cache - parent of #479
- [x] Add storage to the FileCreated and FileUpdated events - parent of #485
- [x] Implement save/fetch from the local storage
- [x] Implement save/fetch from the S3 storage
- [x] Add route for uploading a file from local disk to a specific storage - parent of #475
- [x] Add route for downloading a file from specific storage to local disk - parent of #476
- [x] Add route for creating/updating a file resource against a file which already exists on a specific 
storage (linking) - parent of #477
- [x] Add route for creating a storage
- [x] Add external disk storage - parent of #599

**Comment by umbreak** [comment]
## Storages
Those are resources in the platform that describe where files will be stored.
#### Storage deprecation
When a storage gets deprecated, it cannot be used anymore to create/update files. However, it can still be used to fetch files which where uploaded before the deprecation.

### FileStorage
This type of storage is used to describe how files can be stored in the local file system.

#### Internal json representation
```
{
  "@context": [
    "https://bluebrain.github.io/nexus/contexts/storage.json",
    "https://bluebrain.github.io/nexus/contexts/resource.json"
  ],
  "@id": "{storageId}",
  "@type": [
    "FileStorage",
    "Storage",
  ],
  "algorithm": "{algorithm}",
  "default": {default},
  "volume": "{volume}"
}
```
where...
- `{storageId}`: Iri - The @id of the storage
- `{algorithm}`: String - The digest algorithm
- `{default}`: Boolean - The flag to decide whether or not this storage is the default storage for the project
- `{volume}`: String - The path to the location in the file system where the files are going to be stored

#### Create storage
PUT or POST `/storages/{org_label}/{project_label}/{storageId}` 
```
{  
  "@type": "FileStorage",
  "algorithm": "{algorithm}",
  "default": {default},
  "volume": "{volume}"
}
```

### S3Storage

This type of storage is used to describe how files can be stored in AWS S3 or any compatible blob store.

#### Internal json representation
```
{
  "@context": [
    "https://bluebrain.github.io/nexus/contexts/storage.json",
    "https://bluebrain.github.io/nexus/contexts/resource.json"
  ],
  "@id": "{storageId}",
  "@type": [
    "S3Storage",
    "Alpha",
    "Storage",
  ],
  "algorithm": "{algorithm}",
  "default": {default},
  "bucket": "{bucket}",
  "accessKey": "{accessKey}",
  "secretKey": "{secretKey}",
  "region": "{region}"
}
```
where...
- `{storageId}`: Iri - The @id of the storage
- `{algorithm}`: String - The digest algorithm. Only MD5 supported.
- `{default}`: Boolean - The flag to decide whether or not this storage is the default storage for the project
- `{bucket}`: String - The S3 bucket name
- `{accessKey}`: String - The S3 access key id
- `{secretKey}`: String - The S3 secret access key
- `{region}`: String - The S3 region

#### Create storage
PUT or POST `/storages/{org_label}/{project_label}/{storageId}` 
```
{  
  "@type": ["S3Storage", "Alpha"],
  "default": {default},
  "bucket": "{bucket}",
  "accessKey": "{accessKey}",
  "secretKey": "{secretKey}",
  "region": "{region}"
}
```

**Comment by umbreak** [comment]
The storage is used when uploading files, through the `files` endpoints.

## Upload file to a storage
PUT `/files/{org_label}/{project_label}/{fileId}?storage={storage_id}` (also possible through POST)
... where `{storage_id}` is the `@id` value of an existing storage.
If the query parameter is not present, we will use the latest storage with `default = true`.

## Fetch file from a storage
GET `/files/{org_label}/{project_label}/{fileId}`
The storage is not specified when downloading files because this information it is present in the file event.

## Linking an existing file (in the storage)
PUT `/files/{org_label}/{project_label}/{fileId}` (also possible through POST)
```json
{
  "@type": "LinkFile"
   "source": "{path_to_file}"
}
```
Nexus will issue a query to the storage in order to fetch the metadata required for the file Event (size and hash value) and will answer the client with `resource created` (unless the file does not exist on the storage).

## Linking an existing file (in the storage) and move it to the default location. Only available for create operations.
PUT `/files/{org_label}/{project_label}/{fileId}` (also possible through POST)
```json
{
  "@type": "LinkAndMoveFile"
   "source": "{path_to_file}"
}
```
The following steps are required:
1 - Issue a query to the storage in order to fetch the metadata required for the file Event (size and hash value). 
2- Issue a query to the storage in order to copy the file from the provided `{path_to_file}` to the default destination (configured by the storage).
3 - Verify the hash
4 - Create a Progress Coordinator where we keep track of the progress of a certain operation. Give each progress a UUID and respond to the client with:
```
202 Accepted
Location: /progress/{org_label}/{project_label}/{UUID}
```

## Copy an existing file (in the storage) to another storage
PUT `/files/{org_label}/{project_label}/{fileId}?storage={target_storage_id}`

The following steps are required:
1- Stream the file from the source storage to the target storage
3 - Verify the hash on the target storage
4 - Create a Progress Coordinator where we keep track of the progress of a certain operation. Give each progress a UUID and respond to the client with:
```
202 Accepted
Location: /progress/{org_label}/{project_label}/{UUID}
```
## Checking progress (for async operations)
GET `/progress/{org_label}/{project_label}/{UUID}`
where the responses could be...
```
{
   "@id": {progressId},
   "@type": ["InProgress"],
   "progress": "{progress}"
}
```
or if it already finished:
```
301 Moved Permanently
Location: /files/{org_label}/{project_label}/{fileId}
```

**Comment by bogdanromanx** [comment]
This looks very good, a couple of comments and questions though:

- I'd recommend the use of`/v1/async/` instead of `/v1/progress/` because it's a bit more generic and we can then continue to use the same base for all asynchronous operations
- I think we need to reconsider the term _Linking_
- `Linking` or `linking and moving` should be transparent to the client and controlled by the storage backend; I think for some storage backends a move will not make sense, while for others it will be mandatory. I think the type should not involve a qualifier for intent.
- how are revisions generated when creating a file replica? is it a new revision with the new location or a file will support two locations at the same time?
- api keys and secrets for s3 storage require encryption, how will that be achieved?
- how are the existing files handled by the new implementation?
- what happens if you deprecate an existing storage? can you un-deprecate it?
- what sort of acls are required for creating/updating/deprecating storages
- will we use acls to control who can write files to certain storages?
- how do we handle cases when api keys / secrets expire? how can we make that information available to the client?
- how do we handle cases where the hashes computed when creating a replica will not match, a retry will be automatically triggered? what about when the storages use different hashing algorithms?
- how can we expose the physical location of the file on the storage to the client? is it controlled by the backend or by acls?
- what are the proposed changes to the file metadata?
- how can we handle updates to the files within the same storage? will we use some sort of name mangling scheme to allow multiple revisions of the same file reside on the same storage?
- when "linking" an existing file, do we need to or are we allowed to change the name of the file on disk?
- I think checking the progress for async operations should return some useful information, like how many bytes have been copied out of how many
- how are async operations handled by the system? are they using the primary store to keep the state of the operation? I'm trying to figure out what happens if the system becomes unavailable during a file transfer.
- will any compression schemes be used to minimize bandwidth when transferring data in between storages or storages and clients?

**Comment by umbreak** [comment]
> how are revisions generated when creating a file replica? is it a new revision with the new location or a file will support two locations at the same time?

Revisions are handled like now, meaning that a new file with a new `filePath` will reside on the new storage while keeping the old one on the previous storage (even when it is a copy and both files are the same).

---

> api keys and secrets for s3 storage require encryption, how will that be achieved?

symmetric encryption with some key.

---

> how are the existing files handled by the new implementation?

They belong to the `FileStorage` and they'll be handled as so.

---

> what happens if you deprecate an existing storage? can you un-deprecate it?

That's already explained: No new writes (create/update/link/move) to a file against that storage. Fetches are still allowed. No resources on kg can be un-deprecated (for now), and storages are not special resources. So, no, you won't be able to un-deprecate it. However you can just create a new one.

---

>  what sort of acls are required for creating/updating/deprecating storages

- `file-storage/write` -> allows: creation/updating/tagging/linking/moving files on a `FileStorage`
- `file-storage/read` -> allows: fetching files on a `FileStorage`
- `s3-storage/write` -> allows: creation/updating/tagging/linking/moving files on a `S3Storage`
- `files3storage/read` -> allows: fetching files on a `S3Storage`

---

> how do we handle cases when api keys / secrets expire? how can we make that information available to the client?

With the appropriate rejection when attempting to interact with the storage (write operations)

---

> how do we handle cases where the hashes computed when creating a replica will not match, a retry will be automatically triggered? what about when the storages use different hashing algorithms?

Some storages are limited to a certain hashes. For example, you cannot create an `S3Storage` with `SHA-256` algorithm. That's controlled by configuration.
If the hash fail we will retry, signaling as so in the progress:
```json
{
   "@type": "InProgress",
   "transferedBytes": 100,
   "totalBytes": 2048,
   "startTime": "2018-08-23T16:34:47.143",
   "retryCount": 1,
   "previousError": "Hash did not match the source and target paths"
}
```

---

> how can we handle updates to the files within the same storage? will we use some sort of name mangling scheme to allow multiple revisions of the same file reside on the same storage?

As we do now, having the revision as part of the name/folder structure.

---
> when "linking" an existing file, do we need to or are we allowed to change the name of the file on disk?

No, I don't see the use case. The filename taken will be the name existing on the linked file.

---
> I think checking the progress for async operations should return some useful information, like how many bytes have been copied out of how many

Yes, I updated that. However, it really depends on the store and the way how the copy is made. If the copy is orchestrated by nexus (the stream goes through nexus) they we have this information. If in some cases we issue the copy to the 3rd party store API (e.g.: S3 the same bucket), we might not have this information accessible through the 3rd party store API.

---

> will any compression schemes be used to minimize bandwidth when transferring data in between storages or storages and clients?

As now? GZIP on the HTTP channel

**Comment by hygt** [comment]
> what are the proposed changes to the file metadata?

Internally we need to deal with different kinds of URI and we'll change the event attribute `filePath` to `location`.

```js
{
  "@type": "FileCreated",
  "id": "https://bbp.epfl.ch/nexus/data/resourceName",
  "project": "{project_uuid}",
  "attributes": {
    "uuid": "{file_uuid}",
    "location": "file:///some/path", // could be "s3://some/path", "gpfs:///some/path", ...
    "filename": "{file_name}",
    "mediaType": "application/json",
    "bytes": {file_length},
    "digest": {
      "algorithm": "md5",
      "value": "1234"
    }
  },
  "instant": "{timestamp}",
  "subject": { ... },
  "rev": 1
}
```

We need to decide if we expose this `location` in the attachment metadata exposed by the API.

**Comment by umbreak** [comment]
We also need the storage information:
```json
{
  "@type": "FileCreated",
  "id": "https://bbp.epfl.ch/nexus/data/resourceName",
  "project": "{project_uuid}",
   "storage": {
      ....
   },
   "attributes": {
    "uuid": "{file_uuid}",
    "location": "file:///some/path", // could be "s3://some/path", "gpfs:///some/path", ...
    "filename": "{file_name}",
    "mediaType": "application/json",
    "bytes": {file_length},
    "digest": {
      "algorithm": "md5",
      "value": "1234"
    }
  },
  "instant": "{timestamp}",
  "subject": { ... },
  "rev": 1
}
```
