### ISSUE TITLE
Composite views

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#749]
Each task represents an iteration over the view resources:

- [x] Simple composite view - parent of #747
- [x] Ability to manually restart view - parent of #728 
- [x] Support to query all the projections at once parent of #917
- [x] Support for interval restart strategy - parent of #919
- [x] Support for cross project sources - parent of #748
- [x] Support for RemoteProjectEventStream - parent of #998
