### ISSUE TITLE
Error Messages & Feedback Improvments

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#798]
Show more precise error messages, for example when a resource cannot be loaded, or when a resource is created. 

Error messages should be enriched by the API error response. 

Errors for Sparql and Elastic search queries should provide relevant feedback from the API response. 

Error messages should be managed in a way they don't clutter the UI. 

- [x] Resource Creation Error Handling
- [x] Sparql Error Handling - resolved earlier by https://github.com/BlueBrain/nexus-web/pull/414
- [x] Elastic Search Error Handling - resolved earlier by https://github.com/BlueBrain/nexus-web/pull/414

feedback as provided from: @annakristinkaufmann, @pafonta , @jonathanlurie

**Comment by pafonta** [comment]
Thanks for taking into account our feedback.

I am available for user acceptance testing.
