### ISSUE TITLE
Resource Graph Navigation

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#820]
Part of #851 

AS A technical user
I WANT TO be able to display my resource instance in a graph
SO I CAN see how it relates to other resources visually

## Acceptance criteria
- user can see outgoing links.
- links are displayed as nodes, with edges describing their paths (paths as in the paths from the ResourceLink API).
- nodes are visually distinguishable based on external and internal.
- nodes can be expanded to include that resource's outgoing links as well
- nodes can be un-expanded
- by interacting with a node, the user can navigate to that resource's detail view

------
## Story 📖
- [x] story #825 
- [x] story #827 
- [x] story #828
- [x] story #829
- [x] story #848
- [x] story #854 
- [x] story #870
## Feedback ⚡️🎸🔊
- [x] feedback https://github.com/BlueBrain/nexus/issues/862
- [x] feedback https://github.com/BlueBrain/nexus/issues/863
- [x] feedback https://github.com/BlueBrain/nexus/issues/864
- [x] feedback #871 
- [x] feedback https://github.com/BlueBrain/nexus/issues/876
- [ ] feedback https://github.com/BlueBrain/nexus/issues/877
- [ ] feedback https://github.com/BlueBrain/nexus/issues/878
- [x] feedback https://github.com/BlueBrain/nexus/issues/879
- [x] feedback https://github.com/BlueBrain/nexus/issues/880
- [x] feedback https://github.com/BlueBrain/nexus/issues/882
- [ ] feedback https://github.com/BlueBrain/nexus/issues/883
- [x] feedback https://github.com/BlueBrain/nexus/issues/884
- [x] feedback https://github.com/BlueBrain/nexus/issues/888
- [ ] feedback https://github.com/BlueBrain/nexus/issues/894
## Bugs 🐛
- [x] bug https://github.com/BlueBrain/nexus/issues/881
