### ISSUE TITLE
Resource Instance Relationship Visualization

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#830]
AS A technical user
I WANT TO be able to see the relationships between specific resource instances
SO THAT I CAN understand how they're related without keeping that data in my head
AND SO THAT I CAN navigate to their linked resource instances

- [ ] Navigate to Graph View  #825 
- [ ] Resource As Nodes #827 
- [ ] Expand nodes in the graph #828
- [ ] Navigate to other resources in the graph  #829
- [ ] Persist the graph #826

**Comment by julienmachon** [comment]
Duplicate of #820
