### ISSUE TITLE
Studio wizard

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#902]
AS A technical user
I WANT TO be able to use a step form
SO I CAN create and edit a studio in a guided fashion

----

GIVEN I have want to create a new studio
WHEN I press the "create a new studio" button
THEN I launch a step form or wizard to start the creation process

## Dashboard Editing / Creating
- [x] https://github.com/BlueBrain/nexus/issues/925 Dashboard Edit Button
- [x] https://github.com/BlueBrain/nexus/issues/926 Dashboard query config editor
- [x] https://github.com/BlueBrain/nexus/issues/927 Dashboard view config editing
## Workspace Editing / Creating
- [ ] https://github.com/BlueBrain/nexus/issues/931 Edit Workspace modal and form
- [x] https://github.com/BlueBrain/nexus/issues/932 Add workspace button
## Studio Editing / Creating
- [x] https://github.com/BlueBrain/nexus/issues/929 Create Studio modal
- [x] https://github.com/BlueBrain/nexus/issues/930 Edit Studio button

**Comment by julienmachon** [comment]
We should use something like https://ant.design/components/steps/
