### ISSUE TITLE
Studio: Bulk download

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#915]
AS A domain specific user
I WANT TO select entity rows from studio
SO I CAN download the associated entity data

- [x] Download only the rows and fields available in a Dashboard listing: https://github.com/BlueBrain/nexus/issues/1744
- [ ] Download the listed resource's metadata
- [ ] Download the files

------
GIVEN I have access to a configured studio
WHEN I select a dashboard
THEN I get the ability to select one or more entities for download

GIVEN there is a list of entities
WHEN I select one or more of them
THEN I see a "download" button that I can click

GIVEN I have selected one or more entities from a dash board
WHEN I click the "download" button
THEN I expect my browser to download an archive or csv file

**Comment by adulbrich** [comment]
Solved by data cart and data tables
