### ISSUE TITLE
Nexus Plugins for studio

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#949]
AS A Developer
I WANT to develop my own plugins
SO I can visualise resources in a custom way

AS A Technical user
I WANT to configure studio
SO IT renders custom plugins in the resource detail view

----

GIVEN a list of available plugins
WHEN I create a dashboard
THEN then I can select plugins from the list

GIVEN I have create a dashboard with plugins
WHEN I select an entity from the dashboard table
THEN the matching plugin (based on `@type`) should render

----

- [x] https://github.com/BlueBrain/nexus/issues/950
- [x] https://github.com/BlueBrain/nexus/issues/951
- [x] https://github.com/BlueBrain/nexus/issues/952
- [x] https://github.com/BlueBrain/nexus/issues/953
- [x] https://github.com/BlueBrain/nexus/issues/956
