### ISSUE TITLE
Product Page Revision

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#989]
Align release with paper release
- [x] SEO Structure: https://docs.google.com/presentation/d/1CCqYM9kieLSBjzlxEp84uuNQiK3iCtfydtXm0xZX1nw/edit?pli=1#slide=id.p
- [x] Mockup (layout): https://xd.adobe.com/view/e18c16c4-4526-4f04-6752-4600e687d59c-97bd/
- [x] Design 
- [x] Architecture
- [x] Implementation

Initial changes in content:
- [x] include Nexus Ecosystem components in current product page https://github.com/BlueBrain/nexus/issues/1183

**Comment by adulbrich** [comment]
/index.hmtl
/product/nexus-fusion
/product/nexus-forge
/product/nexus-delta
/use-case/epfl-bbp
/use-case/kcni-camh
/use-case/hbp
/faq
/docs
