### ISSUE TITLE
Nexus Web Refactor (incl. Studio)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#993]
- [x] Design Session (22/01)

- [x] Mockups in Xd (22-23/01)

- [x] Validate mockups with NSE (23-24/01)
https://xd.adobe.com/view/0e3a8dfb-e900-4078-6723-6f46ca71c33d-780b/

- [x] Create initial user stories/backlog (25-27/01)
https://github.com/BlueBrain/nexus/issues/1001
https://github.com/BlueBrain/nexus/issues/1002
https://github.com/BlueBrain/nexus/issues/1003
https://github.com/BlueBrain/nexus/issues/1010
https://github.com/BlueBrain/nexus/issues/1012

- [x] Start development (Week 5)

- [x] Deploy v1 to staging (Week 6) 

- [ ] Deploy v1 to production with v1.3
